# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  # 定时触发 - 每隔一小时触发一次 
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: 填充并验证 Cookies JSON
      env:
        SESSDATA: ${{ secrets.SESSDATA }}
        BILI_JCT: ${{ secrets.bili_jct }}
        DEDEUSERID: ${{ secrets.DedeUserID }}
      run: |
        # 1. 执行替换并写回原文件
        jq -n \
          --arg sd "$SESSDATA" \
          --arg bj "$BILI_JCT" \
          --arg du "$DEDEUSERID" \
          '{SESSDATA: $sd, bili_jct: $bj, DedeUserID: $du}' > cookies.json
        
        # 2. 打印文件内容以便在 GitHub Actions 日志中确认
        echo "--- 填充后的 cookies.json 内容如下 ---"
        cat cookies.json
    - name: run app
      run: |
        python main.py 
